// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Card is an autogenerated mock type for the Card type
type Card struct {
	mock.Mock
}

// Credit provides a mock function with given fields: fare
func (_m *Card) Credit(fare float32) {
	_m.Called(fare)
}

// Debit provides a mock function with given fields: fare
func (_m *Card) Debit(fare float32) error {
	ret := _m.Called(fare)

	var r0 error
	if rf, ok := ret.Get(0).(func(float32) error); ok {
		r0 = rf(fare)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Balance provides a mock function with given fields:
func (_m *Card) Balance() float32 {
	ret := _m.Called()

	var r0 float32
	if rf, ok := ret.Get(0).(func() float32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float32)
	}

	return r0
}

// HasSufficientBalance provides a mock function with given fields: fare
func (_m *Card) HasSufficientBalance(fare float32) bool {
	ret := _m.Called(fare)

	var r0 bool
	if rf, ok := ret.Get(0).(func(float32) bool); ok {
		r0 = rf(fare)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
