// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	station "ostercard/internal/station"

	mock "github.com/stretchr/testify/mock"

	transport "ostercard/internal/transport"
)

// Fare is an autogenerated mock type for the Fare type
type Fare struct {
	mock.Mock
}

// ChargeAfterJourney provides a mock function with given fields: transportType, startPoint, endPoint
func (_m *Fare) ChargeAfterJourney(transportType transport.Transport, startPoint station.StationName, endPoint station.StationName) {
	_m.Called(transportType, startPoint, endPoint)
}

// ChargeBeforeJourney provides a mock function with given fields: transportType
func (_m *Fare) ChargeBeforeJourney(transportType transport.Transport) error {
	ret := _m.Called(transportType)

	var r0 error
	if rf, ok := ret.Get(0).(func(transport.Transport) error); ok {
		r0 = rf(transportType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
