// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	station "ostercard/internal/station"

	mock "github.com/stretchr/testify/mock"

	transport "ostercard/internal/transport"
)

// Journey is an autogenerated mock type for the Journey type
type Journey struct {
	mock.Mock
}

// End provides a mock function with given fields: endPoint
func (_m *Journey) End(endPoint station.StationName) error {
	ret := _m.Called(endPoint)

	var r0 error
	if rf, ok := ret.Get(0).(func(station.StationName) error); ok {
		r0 = rf(endPoint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Start provides a mock function with given fields: _a0, startPoint
func (_m *Journey) Start(_a0 transport.Transport, startPoint station.StationName) error {
	ret := _m.Called(_a0, startPoint)

	var r0 error
	if rf, ok := ret.Get(0).(func(transport.Transport, station.StationName) error); ok {
		r0 = rf(_a0, startPoint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
