// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	"ostercard/internal/station"

	mock "github.com/stretchr/testify/mock"
)

// Station is an autogenerated mock type for the Station type
type Station struct {
	mock.Mock
}

// Zone provides a mock function with given fields: name
func (_m *Station) Zone(name station.StationName) station.Zone {
	ret := _m.Called(name)

	var r0 station.Zone
	if rf, ok := ret.Get(0).(func(station.StationName) station.Zone); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(station.Zone)
		}
	}

	return r0
}
